
var tableName = "fin_salary"; // 当前表名称
var dictionary = {}; // 数据字典
var baseURL = contextPath + "/finance/salary"; // 基URL
var tableDataTable = {}; // 表格对象
var tableElementId = "table-fin_salary"; // 当前表名称
var modalElementId = "modal-fin_salary"; // 当前表名称


/**
 * 页面初始化
 */
$(document).ready(function(){
	
	// 获取数据字典
	//dictionary = bbj.getBBJEntityDictionary(tableName);
	
	// 加载编辑新增页面
	//$("#"+modalElementId).html(bbj.getModalContent(dictionary));
	
	// 初始化控件
	// Utils.initWidgets();
	
	// 初始化表格
	initTable();
	
});


/**
 * 初始化表格数据
 * @param dictionary
 * @returns
 */
function initTable(){
	// 获取配置信息[默认全部进行展示，当数据库新增表结构时候会进行同步更新展示]
	tableDataTable = $('#'+tableElementId).DataTable({
		ajax: { 
            url: baseURL
        },
        scrollX: true,
        lengthChange: false,
 		columns:  [
 			
 			{ "data": "attr.summer_hot" },
            { "data": "attr.summer_hot" },
            { "data": "attr.summer_hot" },
 			
            { "data": "attr.base_salary" },
            { "data": "attr.merit_pay" },
            { "data": "attr.job_type_add" },
            { "data": "attr.serve_age" },
            { "data": "attr.professor_add" },
            { "data": "attr.add_cut" },
            { "data": "attr.food_site" },
            { "data": "attr.food_office" },
            { "data": "attr.weekends_add" },
            { "data": "attr.festival_add" },
            
            { "data": "attr.site_add" },
            { "data": "attr.remote_add" },
            { "data": "attr.tired_add" },
            { "data": "attr.add_cut2" },
            { "data": "attr.draw_percent" },
            { "data": "attr.drive_amount" },
            { "data": "attr.work_amount" },
            { "data": "attr.add_cut3" },
            { "data": "attr.bonus_safe" },
            { "data": "attr.bonus_check" },
            
            { "data": "attr.bonus_certificate" },
            { "data": "attr.bonus_communicate" },
            { "data": "attr.bonus_hot" },
            { "data": "attr.travel_expense" },
            { "data": "attr.computer" },
            { "data": "attr.bonus_annual" },
            //{ "data": "attr.merit_pay2" },
            { "data": "attr.good_start" },
            { "data": "attr.spring_festival" },
            { "data": "attr.company_peer" },
            
            { "data": "attr.mid_autumn" },
            { "data": "attr.dragon_boat_festival" },
            { "data": "attr.bonus_drive_class" },
            { "data": "attr.double_beyond_half" },
            { "data": "attr.summer_hot" },
            { "data": "attr.special1" },
            { "data": "attr.special2" },
            { "data": "attr.special3" },
            { "data": "attr.special4" },
            { "data": "attr.total" },
            
            { "data": "attr.insurance_self" },
            { "data": "attr.public_reserve_funds_self" },
            { "data": "attr.person_income_tax" },
            { "data": "attr.withhold" },
            { "data": "attr.fact_total" },
            
            { "data": "attr.summer_hot" },
            { "data": "attr.summer_hot" },
            { "data": "attr.summer_hot" },
            { "data": "attr.summer_hot" },
            
            { "data": "attr.insurance_com" },
            { "data": "attr.public_reserve_funds_com" },
        ] 
	});
}


/**
 * 插入[新增]操作
 * @returns
 */
function insertOption(){
	bbj.setBBJEntityValue({},dictionary); // 清空Form数据
	$("#"+modalElementId).modal('show'); // 打开输入Form模态框
}


/**
 * 删除操作
 * @param id
 * @returns
 */
function deleteOption(id){
	Utils.ajax({ 
 		url : baseURL + "/" + id,
		type : 'DELETE',
		success : function(data) {
			tableDataTable.draw(false);// 刷新页面
		}
	});
}


/**
 * 更新[修改]操作
 * @param id
 * @returns
 */
function updateOption(id){
	// 根据主键获取对应行数据
	Utils.ajax({ 
		url : baseURL + "/" + id,
		type : 'GET',
		success : function(data) {
			bbj.setBBJEntityValue(data.data,dictionary); // 设置Form值
			$("#"+modalElementId).modal('show'); // 打开输入Form模态框
		}
	});
}


/**
 * 新增或修改保存函数
 * @returns
 */
function insertOrUpdateSave(){
	$("#"+modalElementId).modal('hide'); // 隐藏Form模态框
	var entity= bbj.getBBJEntityValue(dictionary); // 获取输入的值
	
	var type = "POST"; // 新增操作
	if (entity.id) { // 如果主键不为有效
		type = "PUT"; // 修改操作
	}
	// 提交给后台进行保存
	Utils.ajax({ 
		type : type,
		url : baseURL,
		data : entity,
		success : function(data) {
			tableDataTable.draw(false);// 刷新页面
		}
	});
}

function getDictionary(){
	var dictionary = [
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:16:37.0",
					"field_type_comment" : "基本工资",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "base_salary",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : "2018-09-28 21:19:11.0",
					"field_name_comment" : "基本工资",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140597834",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:16:58.0",
					"field_type_comment" : "绩效工资",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "merit_pay",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "绩效工资",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140618392",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:17:11.0",
					"field_type_comment" : "职务补贴",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "job_type_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "职务补贴",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140631590",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:17:24.0",
					"field_type_comment" : "工龄工资",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "serve_age",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "工龄工资",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140644416",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:17:38.0",
					"field_type_comment" : "专家/炊事员费用",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "professor_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "专家/炊事员费用",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140658713",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:18:58.0",
					"field_type_comment" : "补或扣",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "add_cut",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "补或扣",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538140738938",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "float",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:31:13.0",
					"field_type_comment" : "伙补（现场）/月度",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "food_site",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "伙补（现场）/月度",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141473278",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "float",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:31:37.0",
					"field_type_comment" : "伙补（机关）/季度",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "food_office",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "伙补（机关）/季度",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141497331",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:32:04.0",
					"field_type_comment" : "周末加班",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "weekends_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "周末加班",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141524276",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:32:14.0",
					"field_type_comment" : "假日加班",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "festival_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "假日加班",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141534919",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:32:26.0",
					"field_type_comment" : "驻点补助",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "site_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "驻点补助",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141546011",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:32:41.0",
					"field_type_comment" : "远程补助",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "remote_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "远程补助",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141561034",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:32:58.0",
					"field_type_comment" : "艰苦地区补助",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "tired_add",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "艰苦地区补助",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141578141",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:33:31.0",
					"field_type_comment" : "补或扣2",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "add_cut2",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "补或扣2",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141611137",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:34:31.0",
					"field_type_comment" : "提成保底奖金",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "draw_percent",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "提成保底奖金",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141671346",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:34:41.0",
					"field_type_comment" : "驾驶员公里费",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "drive_amount",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "驾驶员公里费",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141681347",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:34:51.0",
					"field_type_comment" : "工作量奖金",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "work_amount",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "工作量奖金",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141691533",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:35:07.0",
					"field_type_comment" : "补或扣3",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "add_cut3",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "补或扣3",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141707078",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:36:00.0",
					"field_type_comment" : "安全生产奖",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_safe",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "安全生产奖",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141760384",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:36:11.0",
					"field_type_comment" : "月度考核",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_check",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "月度考核",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141771190",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:36:31.0",
					"field_type_comment" : "证书津贴/季度",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_certificate",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "证书津贴/季度",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141791269",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:36:40.0",
					"field_type_comment" : "通讯奖励/季度",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_communicate",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "通讯奖励/季度",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141800017",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:36:59.0",
					"field_type_comment" : "高温费",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_hot",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "高温费",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141819569",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:37:09.0",
					"field_type_comment" : "差旅费",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "travel_expense",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "差旅费",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141829113",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:37:34.0",
					"field_type_comment" : "电脑自购补助",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "computer",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "电脑自购补助",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141854750",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:37:47.0",
					"field_type_comment" : "年终奖",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_annual",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "年终奖",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141867151",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:37:59.0",
					"field_type_comment" : "绩效工资考核部分",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "merit_pay",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "绩效工资考核部分",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141879341",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:38:20.0",
					"field_type_comment" : "开门红",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "good_start",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "开门红",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141900209",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:38:32.0",
					"field_type_comment" : "春节过节费",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "spring_festival",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "春节过节费",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141912042",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:38:43.0",
					"field_type_comment" : "公司先进",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "company_peer",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "公司先进",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141923681",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:38:58.0",
					"field_type_comment" : "中秋过节费",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "mid_autumn",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "中秋过节费",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141938249",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:39:44.0",
					"field_type_comment" : "端午节",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "dragon_boat_festival",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "端午节",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141984210",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:39:58.0",
					"field_type_comment" : "驾驶班补助",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "bonus_drive_class",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "驾驶班补助",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538141998900",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:40:08.0",
					"field_type_comment" : "双过半奖",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "double_beyond_half",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "双过半奖",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142008158",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:40:18.0",
					"field_type_comment" : "迎峰度夏奖",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "summer_hot",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "迎峰度夏奖",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142018778",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:40:32.0",
					"field_type_comment" : "专1",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "special1",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "专1",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142032650",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:40:42.0",
					"field_type_comment" : "专2",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "special2",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "专2",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142042505",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:40:53.0",
					"field_type_comment" : "专3",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "special3",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "专3",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142053160",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:41:04.0",
					"field_type_comment" : "专4",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "special4",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "专4",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142064336",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:41:15.0",
					"field_type_comment" : "合计",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "total",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "合计",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142075801",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:41:34.0",
					"field_type_comment" : "保险个缴",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "insurance_self",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "保险个缴",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142094120",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:41:44.0",
					"field_type_comment" : "公积金个缴",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "public_reserve_funds_self",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "公积金个缴",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142104270",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:41:55.0",
					"field_type_comment" : "个税",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "person_income_tax",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "个税",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142115964",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:42:05.0",
					"field_type_comment" : "扣款",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "withhold",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "扣款",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142125532",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:42:17.0",
					"field_type_comment" : "实际合计",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "fact_total",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "实际合计",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142137188",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:42:31.0",
					"field_type_comment" : "保险企缴",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "insurance_com",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "保险企缴",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142151041",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			},
			{
				"tableName" : "admin_dictionary_field",
				"attr" : {
					"delete_state" : "0",
					"create_time" : "2018-09-28 21:42:41.0",
					"field_type_comment" : "公积金企缴",
					"field_reference_table_field_name" : null,
					"update_staff_id" : null,
					"field_constraint" : null,
					"table_name" : "fin_salary",
					"field_name" : "public_reserve_funds_com",
					"field_reference_table_field_value" : null,
					"field_show_type_comment" : null,
					"create_staff_id" : null,
					"update_time" : null,
					"field_name_comment" : "公积金企缴",
					"field_reference_table_name" : null,
					"field_order_number" : null,
					"id" : "1538142161350",
					"field_show_type" : "label",
					"field_constraint_comment" : null,
					"field_type" : "varchar(64)",
					"field_reference_comment" : null
				},
				"id" : "id",
				"attrKeysStr" : "delete_state,create_time,field_type_comment,field_reference_table_field_name,update_staff_id,field_constraint,table_name,field_name,field_reference_table_field_value,field_show_type_comment,create_staff_id,update_time,field_name_comment,field_reference_table_name,field_order_number,id,field_show_type,field_constraint_comment,field_type,field_reference_comment",
				"attrKeys" : [ "delete_state", "create_time",
						"field_type_comment",
						"field_reference_table_field_name", "update_staff_id",
						"field_constraint", "table_name", "field_name",
						"field_reference_table_field_value",
						"field_show_type_comment", "create_staff_id",
						"update_time", "field_name_comment",
						"field_reference_table_name", "field_order_number",
						"id", "field_show_type", "field_constraint_comment",
						"field_type", "field_reference_comment" ]
			} ];
	return dictionary;
}
